### ISSUE TITLE
problem of catkin

### ISSUE THREAD

**Issue by cheesekuntly** [wangyuanbiubiubiu/ICE-BA-ros#1]
I had a problem when I run catkin_make
It shows :
/home/tan/catkin_ws/src/ICE-BA/Backend/IBA/IBA.h:91:8: note:   candidate expects 1 argument, 0 provided
ICE-BA/App/CMakeFiles/ice_ba.dir/build.make:62: recipe for target 'ICE-BA/App/CMakeFiles/ice_ba.dir/EuRoC_test.cpp.o' failed
make[2]: *** [ICE-BA/App/CMakeFiles/ice_ba.dir/EuRoC_test.cpp.o] Error 1
CMakeFiles/Makefile2:2498: recipe for target 'ICE-BA/App/CMakeFiles/ice_ba.dir/all' failed
make[1]: *** [ICE-BA/App/CMakeFiles/ice_ba.dir/all] Error 2
[100%] Linking CXX executable /home/tan/catkin_ws/src/ICE-BA/bin/back_end
/usr/bin/ld: warning: libgflags.so.2, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libglog.so, may conflict with libgflags.so.2.2
[100%] Built target back_end
[100%] Linking CXX executable /home/tan/catkin_ws/src/ICE-BA/bin/ice_ba_ros
/usr/bin/ld: warning: libgflags.so.2, needed by /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libglog.so, may conflict with libgflags.so.2.2
[100%] Built target ice_ba_ros
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j12 -l12" failed

**Comment by wangyuanbiubiubiu** [comment]
sorry,In EuRoC_test. cpp  "solver.GetMapPointIndexes()" forgot to delete this sentence. I've updated my code, you can directly delete this sentence

**Comment by wangyuanbiubiubiu** [comment]
I did not encounter this problem, it may be the problem of Gflags, do you have any problem running the original iba of baidu?

**Comment by cheesekuntly** [comment]
Thank you for your help,delete the sentence it works.
I have run the original version of baidu,but when I run ice_ba_mono.sh it will show"[E0306 20:10:07.525207 12608 EuRoC_test.cpp:228] convert to asl timestamp error"

**Comment by wangyuanbiubiubiu** [comment]
The version of baidu cannot use mono vio, it needs to be initialized to run. I may add the mono vio and loop closed later.

**Comment by cheesekuntly** [comment]
Do you know how to replace the front end of ice-ba with own monocular vio?just run run_backend_only?

**Comment by wangyuanbiubiubiu** [comment]
No, I use iba as an online slam,but yo can see run_backend_only.sh

**Comment by wangyuanbiubiubiu** [comment]
> Do you know how to replace the front end of ice-ba with own monocular vio?just run run_backend_only?

My mistake, I found that the code supports mono-vio, but you need to move your camera as soon as the program runs, you can see my latest updated code

**Comment by cheesekuntly** [comment]
Thank you for the code,it shows [error while loading shared libraries: libDBoW3.so.0.0: cannot open shared object file: No such file or directory].
And in the original version, the "dat" folder is eampty after save_features  if I want to run backend only mode.

**Comment by wangyuanbiubiubiu** [comment]
Did you use "catkin_make" or "caktin_build"?
Check the "Loopclosure/CMakeLists.txt"
`set(DBoW3_LIBS ${PROJECT_SOURCE_DIR}/../thirdparty/DBoW3/build/src/libDBoW3${CMAKE_SHARED_LIBRARY_SUFFIX})`

`set(opengv_LIBS ${PROJECT_SOURCE_DIR}/../thirdparty/opengv/build/devel/lib/libopengv${CMAKE_SHARED_LIBRARY_SUFFIX})`
If you want If you want to use dat,check`IBA::SaveCurrentFrame(iba_dat_file_paths[it_img], CF, KF);`,and set `save_feature=true`,But in my code, I've removed this, and you can add it after the end of the frontend.

**Comment by cheesekuntly** [comment]
It works~ but how can I save the result when use ros run mode?

**Comment by wangyuanbiubiubiu** [comment]
`pubKFsPose(kf_poses);` in kf_poses,All poses for the GBA are recorded,You can record  kf_pose value in the last  SetCallbackGBA.I will add this option in the next update.

**Comment by cheesekuntly** [comment]
thanks for your awesome work!

**Comment by wangyuanbiubiubiu** [comment]
I've updated my code,set your `GBA_result_path`
