### ISSUE TITLE
Compile errors when build with CFG_STEREO disabled on monocular system.

### ISSUE THREAD

**Issue by lex0880** [wangyuanbiubiubiu/ICE-BA-ros#2]
Hi
I tried to compile with the Flag CFG_STEREO disabled (undefined), but I encountered several compilation errors. Have you ever tried to execute the code for Monocular system based on ARM processor?
Can you help me to execute it on my monocular system?

Thank you

**Comment by wangyuanbiubiubiu** [comment]
Sorry, I haven't compiled on an ARM processor. You can try the source code also has this problem.

**Comment by lex0880** [comment]
Thanks.
I also tried with x86 processor, but I encoutered the same errors.
Is it right to disable the CFG_STEREO Flag to execute the Monocular version?

**Comment by wangyuanbiubiubiu** [comment]
If you want to use a monocular, refer to the following configuration file
[config](https://github.com/wangyuanbiubiubiu/ICE-BA-ros/blob/master/config/euroc/euroc_mono_imu_config.yaml)   
set num_of_cam 1

**Comment by lex0880** [comment]
Thank you.
Now I'm trying to compile ICE-BA algorithm on an ARM-based processor.
